name: Deploy to Lambda function

on:
  push:
    branches: master

env:
  AWS_REGION: eu-west-1
  FUNCTION_NAME: cloud-workshop-lambda
  DEPLOYMENT_PACKAGE: deploy.zip

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -t .

      - name: Create deployment package
        run: |
          zip -r ${{ env.DEPLOYMENT_PACKAGE }} .

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.0.4
        with:
          function_name: ${{ env.FUNCTION_NAME }}
          zip_file: ${{ env.DEPLOYMENT_PACKAGE }}
